--- 
Layout/CaseIndentation: 
  Enabled: false
Layout/ElseAlignment: 
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor: 
  Enabled: true
Layout/EmptyLinesAroundBlockBody: 
  Enabled: false
Layout/EndAlignment: 
  Enabled: true
  EnforcedStyleAlignWith: start_of_line
Layout/FirstArrayElementIndentation: 
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation: 
  EnforcedStyle: consistent
Layout/LineLength: 
  Enabled: false
Layout/MultilineHashBraceLayout: 
  Enabled: true
  EnforcedStyle: symmetrical
Layout/MultilineMethodCallIndentation: 
  EnforcedStyle: indented
Layout/MultilineOperationIndentation: 
  EnforcedStyle: indented
Layout/ParameterAlignment: 
  Enabled: true
  EnforcedStyle: with_fixed_indentation
Layout/SpaceAroundMethodCallOperator: 
  Enabled: true
Layout/SpaceInLambdaLiteral: 
  EnforcedStyle: require_space
Layout/SpaceInsideHashLiteralBraces: 
  EnforcedStyle: no_space
Layout/TrailingWhitespace: 
  Enabled: false
Lint/AmbiguousBlockAssociation: 
  Enabled: false
Lint/AssignmentInCondition: 
  Enabled: false
Lint/DeprecatedOpenSSLConstant: 
  Enabled: false
Lint/MixedRegexpCaptureTypes: 
  Enabled: false
Lint/RaiseException: 
  Enabled: false
Lint/RedundantSplatExpansion: 
  Enabled: false
Lint/StructNewOverride: 
  Enabled: false
Metrics/AbcSize: 
  Enabled: false
Metrics/BlockLength: 
  CountComments: false
  Enabled: true
  Exclude: 
    - spec/**/*_spec.rb
  Max: 100
Metrics/ClassLength: 
  Enabled: false
Metrics/CyclomaticComplexity: 
  Max: 10
Metrics/MethodLength: 
  Enabled: false
Metrics/ModuleLength: 
  Enabled: false
Metrics/PerceivedComplexity: 
  Max: 10
Naming/FileName: 
  Enabled: false
Naming/MethodParameterName: 
  Enabled: false
RSpec/AnyInstance: 
  Enabled: false
RSpec/DescribeClass: 
  Exclude: 
    - spec/requests/**/*_spec.rb
RSpec/DescribeMethod: 
  Enabled: false
RSpec/DescribedClass: 
  Enabled: false
RSpec/ExampleLength: 
  Exclude: 
    - spec/workers/**/*_spec.rb
  Max: 25
RSpec/ImplicitSubject: 
  Enabled: false
RSpec/LetSetup: 
  Enabled: false
RSpec/MessageSpies: 
  Enabled: false
RSpec/MultipleExpectations: 
  Enabled: false
RSpec/NestedGroups: 
  Max: 5
RSpec/NotToNot: 
  EnforcedStyle: to_not
Security/YAMLLoad: 
  Exclude: 
    - app/models/entity.rb
Style/Alias: 
  Enabled: false
Style/AsciiComments: 
  Enabled: false
Style/ClassAndModuleChildren: 
  Enabled: false
Style/Documentation: 
  Enabled: false
Style/EmptyMethod: 
  EnforcedStyle: expanded
Style/ExponentialNotation: 
  Enabled: true
Style/FormatStringToken: 
  Enabled: false
Style/FrozenStringLiteralComment: 
  Enabled: false
Style/HashEachMethods: 
  Enabled: true
Style/HashTransformKeys: 
  Enabled: true
Style/HashTransformValues: 
  Enabled: true
Style/Lambda: 
  Enabled: false
Style/NumericPredicate: 
  Enabled: false
Style/PerlBackrefs: 
  Enabled: false
Style/RedundantRegexpCharacterClass: 
  Enabled: true
Style/RedundantRegexpEscape: 
  Enabled: true
Style/RescueModifier: 
  Enabled: false
Style/SafeNavigation: 
  Enabled: false
Style/SlicingWithRange: 
  Enabled: true
Style/SymbolArray: 
  EnforcedStyle: brackets
require: 
  - rubocop-rspec
  - rubocop-performance
